
try:
    from call_bot.local_settings import DISCORD_BOT_TOKEN, DISCORD_CLIENT_ID
except Exception as e:
    print(e)

