
try:
    from call_bot.local_settings import *
except Exception as e:
    print(e)

